### ISSUE TITLE
wordpress plugin issue: Unexpected end of JSON input

### ISSUE THREAD

**Issue by nezam05** [Mailtrain-org/mailtrain-wordpress-plugin#1]
I am getting this error from the wordpress widget of this plugin
`Unexpected end of JSON input`

**Comment by witzig** [comment]
Just to verify, are you running Mailtrain v1.23.2 plus [this patch](https://github.com/Mailtrain-org/mailtrain/commit/100fd41713c6feab560f167cca4c42588211fade)? Also, when checking  your browsers DevTools Console,  is there any more info?

**Comment by nezam05** [comment]
Mailtrain version is v.1.23.2. Not sure about the patch as I am running on cloudron. 

I was getting a different browser error earlier, something more like err name resolution. now getting this
`(index):1 XMLHttpRequest cannot load https://marketing.pompom.com.bd/subscription/SJy5k0fhe/widget. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://futurestartup.com' is therefore not allowed access. The response had HTTP status code 403.`

**Comment by witzig** [comment]
You need to enable CORS:
> 4. [Enable cross-origin resource sharing](https://github.com/Mailtrain-org/mailtrain#subscription-widget) in your Mailtrain config file and whitelist your site

Yet I'm not sure if you're able to edit the config file on cloudron ...

**Comment by nezam05** [comment]
Its enabled in my installation and the website is whitelisted.

**Comment by witzig** [comment]
`http://futurestartup.com` is not in your whitelist, only `http://www.futurestartup.com` is.

Your config should look like this:

```
[cors]
# Allow subscription widgets to be embedded
origins=["http://futurestartup.com", "http://www.futurestartup.com"]
```

Still, if you want widgets to work with custom forms, you need the patch mentioned above.

**Comment by nezam05** [comment]
Hi, I have modified the config file and it now looks like the above. However, now getting this on browser console
`OPTIONS https://marketing.pompom.com.bdsubscription/SJy5k0fhe/subscribe net::ERR_NAME_NOT_RESOLVED
sendForm @ widget.js?ver=4.7.3:102
(anonymous) @ widget.js?ver=4.7.3:141`

it seems the list url is missing a / after _.com.bd_

**Comment by witzig** [comment]
> it seems the list url is missing a / after .com.bd

Yeah, the cause is [here](https://github.com/Mailtrain-org/mailtrain/blob/v1.23.2/views/subscription/widget-subscribe.hbs#L10), yet the ServiceURL in Mailtrain [should actually save with a trailing slash](https://github.com/Mailtrain-org/mailtrain/blob/v1.23.2/routes/settings.js#L88).

On your Mailtrain Settings Page, could you verify (or manually add) the trailing slash to your Service URL?

**Comment by nezam05** [comment]
Adding a slash solves the issue. Thanks.
