### ISSUE TITLE
Status now showing after submit

### ISSUE THREAD

**Issue by msbt** [Mailtrain-org/mailtrain-wordpress-plugin#2]
Hi there,
thanks for the Plugin! I'm trying to get this to work with a cloudron installation. I've managed to add the [cors] to the container and I see the form on the Wordpress site. But when I hit "Subscribe" the form just disappears (except the title) and leaves the customer clueless. The subscription email gets sent and works, but the status thing which has display:none would be nice to have, any idea what I could do?

Best regards,
M

**Comment by witzig** [comment]
@msbt, I am not able to reproduce the issue.  Do you see any JS errors in the developer console? And which browser are you using?

**Comment by msbt** [comment]
There are no js errors, but I just found a .status class in my theme which screws up everything. Any chance we could add mailtrain prefix to css classes in future versions? Either way, issue is resolved because of a bad WP theme, thanks.
